# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtracker',
            name='showname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
