# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_showtracker_showname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtracker',
            name='showname',
        ),
    ]
