# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_showtracker_showname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='showtracker',
            old_name='showname',
            new_name='venue',
        ),
        migrations.AddField(
            model_name='setlist',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ShowTracker'),
        ),
        migrations.AddField(
            model_name='bandmembers',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ShowTracker'),
        ),
    ]
