# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20170907_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofband', models.CharField(max_length=50, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ShowTracker')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bandmembers',
            old_name='member',
            new_name='instrument',
        ),
        migrations.RenameField(
            model_name='setlist',
            old_name='song',
            new_name='nameofsetlist',
        ),
        migrations.RemoveField(
            model_name='bandmembers',
            name='show',
        ),
        migrations.AddField(
            model_name='bandmembers',
            name='nameofbandmemeber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='setlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Setlist'),
        ),
        migrations.AddField(
            model_name='bandmembers',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Band'),
            preserve_default=False,
        ),
    ]
