# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20170909_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandmembers',
            old_name='nameofbandmemeber',
            new_name='nameofbandmember',
        ),
    ]
